name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.os }} @ Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        go: [1.18, 1.19]
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -coverprofile="coverage.txt" -covermode=atomic -race .

      - name: Upload coverage to Codecov
        if: success() && matrix.go == 1.18 && matrix.os == 'ubuntu-latest'
        # uses: codecov/codecov-action@v1
        run: bash <(curl -s https://codecov.io/bash)
